name: Trigger auto deployment for ca-dwpodcastfeed

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-dwpodcastfeed-AutoDeployTrigger-4fde26be-5bf5-408e-86d7-6a14dec09b65.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CADWPODCASTFEED_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca0a224f3f3cacr.azurecr.io
          registryUsername: ${{ secrets.CADWPODCASTFEED_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CADWPODCASTFEED_REGISTRY_PASSWORD }}
          containerAppName: ca-dwpodcastfeed
          resourceGroup: rg-dwpodcastfeed
          imageToBuild: ca0a224f3f3cacr.azurecr.io/ca-dwpodcastfeed:${{ github.sha }}
          
            

     

